kind: pipeline
name: vim-maven-tests
type: docker
steps:
  - name: build
    pull: if-not-exists
    image: maven:3-jdk-8
    commands:
      - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn test -B