apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vizit-vim
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: vizit-vim
    spec:
      containers:
        - name: vizit-vim
          image: gcr.io/vizit-vim:TAG
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m