apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vim-app
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: vim-app
    spec:
      containers:
        - name: vizit-vim
          image: gcr.io/vizit-vim/vim-app:TAG
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: app-key
                  key: appcredentials.json
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
            - name: spring.datasource.url
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: url
          envFrom:
            - configMapRef:
                name: spring-app-config
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m