apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vim-app
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: vim-app
    spec:
      containers:
        - name: vizit-vim
          image: gcr.io/vizit-vim/vim-app:TAG
          env:
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                    name: db-user-pass
                    key: db-user
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                    name: db-user-pass
                    key: db-pass
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m