version: '3.1'
services:
  vim-database:
    build:
      context: ../
      dockerfile: .docker/database.dockerfile
    container_name: vim_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  vim-maildev:
    image: maildev/maildev
    ports:
      - "9025:25"
      - "9080:80"